<a href="https://colab.research.google.com/github/wahid49/tf-Regression/blob/main/Tensor_and_Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
tensor_zero_d = tf.constant(1)
print(tensor_zero_d)

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2, 0, -3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([[[1,2,0],
                               [3,5,-1]],
                              [[10,2,0],
                               [1,0,2]],
                              [[5,8,0],
                               [2,7,0]],
                              [[2,1,9],
                               [4,3,32]]])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4  3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
import numpy as np

In [ ]:
tensor_four_d = np.zeros(4)

In [ ]:
tf.constant(tensor_four_d)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0., 0., 0., 0.])>

In [ ]:
tensor_four_di = tf.constant(
                            [[[[1,2,0],
                               [3,5,-1]],
                              [[10,2,0],
                               [1,0,2]],
                              [[5,8,0],
                               [2,7,0]],
                              [[2,1,9],
                               [4,3,32]]],
                             
                             [[[1,2,0],
                               [3,5,-1]],
                              [[10,2,0],
                               [1,0,2]],
                              [[5,8,0],
                               [2,7,0]],
                              [[2,1,9],
                               [4,3,32]]],
                             
                             [[[1,2,0],
                               [3,5,-1]],
                              [[10,2,0],
                               [1,0,2]],
                              [[5,8,0],
                               [2,7,0]],
                              [[2,1,9],
                               [4,3,32]]],
                             
                             [[[1,2,0],
                               [3,5,-1]],
                              [[10,2,0],
                               [1,0,2]],
                              [[5,8,0],
                               [2,7,0]],
                              [[2,1,9],
                               [4,3,32]]]])
tensor_four_di, tensor_four_di.shape, tensor_four_di.ndim

(<tf.Tensor: shape=(4, 4, 2, 3), dtype=int32, numpy=
 array([[[[ 1,  2,  0],
          [ 3,  5, -1]],
 
         [[10,  2,  0],
          [ 1,  0,  2]],
 
         [[ 5,  8,  0],
          [ 2,  7,  0]],
 
         [[ 2,  1,  9],
          [ 4,  3, 32]]],
 
 
        [[[ 1,  2,  0],
          [ 3,  5, -1]],
 
         [[10,  2,  0],
          [ 1,  0,  2]],
 
         [[ 5,  8,  0],
          [ 2,  7,  0]],
 
         [[ 2,  1,  9],
          [ 4,  3, 32]]],
 
 
        [[[ 1,  2,  0],
          [ 3,  5, -1]],
 
         [[10,  2,  0],
          [ 1,  0,  2]],
 
         [[ 5,  8,  0],
          [ 2,  7,  0]],
 
         [[ 2,  1,  9],
          [ 4,  3, 32]]],
 
 
        [[[ 1,  2,  0],
          [ 3,  5, -1]],
 
         [[10,  2,  0],
          [ 1,  0,  2]],
 
         [[ 5,  8,  0],
          [ 2,  7,  0]],
 
         [[ 2,  1,  9],
          [ 4,  3, 32]]]], dtype=int32)>, TensorShape([4, 4, 2, 3]), 4)

In [ ]:
tensor_1_d = tf.constant([3,0.5,-3], dtype=tf.float32)
print(tensor_1_d)
# Cast convert float32 to float16
cast_tensor_1_d = tf.cast(tensor_1_d, dtype=tf.float16)
print(cast_tensor_1_d)


tf.Tensor([ 3.   0.5 -3. ], shape=(3,), dtype=float32)
tf.Tensor([ 3.   0.5 -3. ], shape=(3,), dtype=float16)


In [ ]:
x_np = np.array([3,4,5])
print(x_np)

[3 4 5]


In [ ]:
x_tf = tf.convert_to_tensor(x_np, dtype=tf.float32)
print(x_tf)

tf.Tensor([3. 4. 5.], shape=(3,), dtype=float32)


In [ ]:
identity_matrics = tf.eye(8, num_columns=3, batch_shape=[3])
print(identity_matrics)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 8, 3), dtype=float32)


In [ ]:
tensor_fill = tf.fill([2,3], 19)
print(tensor_fill)

tf.Tensor(
[[19 19 19]
 [19 19 19]], shape=(2, 3), dtype=int32)


In [ ]:
tensor_ones = tf.ones([4,3])
print(tensor_ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [ ]:
tensor_zeros = tf.zeros([5,2], dtype=tf.float32)
print(tensor_zeros)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(5, 2), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(tensor_four_di, dtype=tf.float32)
print(ones_like_tensor)

tf.Tensor(
[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]], shape=(4, 4, 2, 3), dtype=float32)


In [ ]:
tf.random_normal_initializer(
    mean=0.0, stddev=0.05, seed=None
)

In [ ]:
tensor_normal_ini = tf.random_normal_initializer(mean=tensor_four_di)
tensor_normal_ini

In [ ]:
start = 3
limit = 18
delta = 3
tf.range(start, limit)

<tf.Tensor: shape=(15,), dtype=int32, numpy=
array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
      dtype=int32)>

In [ ]:
tf.range(3, 25, 6, dtype=tf.float32)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  9., 15., 21.], dtype=float32)>

In [ ]:
num_rows = 3
num_columns = 3
batch_shape = [2]
tf.eye(num_rows, num_columns, batch_shape)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]], dtype=float32)>

In [ ]:
tf.random_normal_initializer(
    mean=0.0, stddev=0.05, seed=None
)


In [ ]:
mean = 4
stddev = 0.1
tf.random_normal_initializer(mean, stddev)

In [ ]:
tf.shape(tensor_four_di)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 4, 2, 3], dtype=int32)>

In [ ]:
tensor_four_di.shape

TensorShape([4, 4, 2, 3])

In [ ]:
print(tf.size(tensor_four_di))

tf.Tensor(96, shape=(), dtype=int32)


In [ ]:
g = tf.random.Generator.from_non_deterministic_state()
g.normal(shape=(2,), mean=100, stddev=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([101.58196,  98.48762], dtype=float32)>

In [ ]:
g.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.0431641 , 0.5755163 , 0.7208353 ],
       [0.11541076, 0.6656553 , 0.20438626]], dtype=float32)>

In [ ]:
g = tf.random.Generator.from_seed(120)
g.uniform(shape=(2,), minval=12, maxval=10)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([11.860489, 10.277416], dtype=float32)>

In [ ]:
tf.random.normal(
    (3,2), mean=4.0, stddev=0.10, dtype=tf.dtypes.float32, seed=42, name=None
)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3.9719224, 3.986225 ],
       [3.932367 , 4.002458 ],
       [3.9106414, 3.9171526]], dtype=float32)>

In [ ]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[1])
print(tensor_indexed[1:3+1])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor([6 2 4], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d[0:3 , 0:2]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 5],
       [1, 5]], dtype=int32)>

In [ ]:
tensor_four_di.ndim

4

In [ ]:
# Work on indexing
ten_two_d = tf.constant([[1,2,3],
                          [3,4,5],
                          [4,7,8],
                         [5,6,7]])
print(ten_two_d[ ...,1])

tf.Tensor([2 4 7 6], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 5,  8,  0],
        [ 2,  7,  0]],

       [[ 2,  1,  9],
        [ 4,  3, 32]]], dtype=int32)>

In [ ]:
print(tensor_three_d[..., :, 2])

tf.Tensor(
[[ 0 -1]
 [ 0  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)


In [ ]:
# real number
x = tf.constant([-2.25, 3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [ ]:
tf.sqrt(-2.25**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=4.1833>

In [ ]:
x_1 = tf.constant([1,2,3,4,5], dtype=tf.int32)
x_2 = tf.constant([6,6,7,8,9], dtype= tf.int32)

tf.multiply(x_1, x_2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6, 12, 21, 32, 45], dtype=int32)>

In [ ]:
# Broadcasting Tensor

x_1 = tf.constant([1,2,3,4,5], dtype=tf.int32)
x_2 = tf.constant([7], dtype= tf.int32)



In [ ]:
xx1 = tf.constant([[5,3,6,6,4,6]], dtype=tf.float32)
xx2 = tf.constant([[7], [5], [3]], dtype=tf.float32)

print(xx1.shape)
print(xx2.shape)
print(tf.math.multiply(xx1,xx2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [ ]:
x_argmax = tf.constant([[2,20,30,3,6],
                        [3,11,16,1,8],
                        [14,45,23,5,27]])
print(x_argmax.shape)
print(tf.math.argmax(x_argmax))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)


In [ ]:
x_argmax = tf.constant([2,20,30,3,6])
print(tf.math.argmin(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)  # [[256, 65536], [9, 27]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
tensor_two_D = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype=tf.float32)
print(tensor_two_D)
tf.math.reduce_mean(tensor_two_D, axis=0, keepdims=False, name=None)

tf.Tensor(
[[  1.  -2.   0.]
 [  3.   5. 100.]
 [  1.   5.   6.]
 [  2.   3.   8.]], shape=(4, 3), dtype=float32)


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 1.75,  2.75, 28.5 ], dtype=float32)>

In [ ]:
tf.math.top_k(tensor_two_D)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[  1.],
       [100.],
       [  6.],
       [  8.]], dtype=float32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[0],
       [2],
       [2],
       [2]], dtype=int32)>)

In [ ]:
x_1 = tf.cast(x_1, dtype=tf.float32)
x_1

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [ ]:
x_1,x_2

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([7], dtype=int32)>)

In [ ]:
print(tf.transpose(x_2))

tf.Tensor([7], shape=(1,), dtype=int32)


In [ ]:
x_1 = tf.constant([[3,5,8]])

x_2 = tf.constant([[1,2,0,2],
                   [4,5,-1,2],
                   [4,5,6,0]])

x_3 = tf.constant([[1,2,0,2],
                   [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)

print(x_3@tf.transpose(x_2))
tf.linalg.matmul(
    x_3, x_2, transpose_a=False, transpose_b=True, adjoint_a=False, adjoint_b=False,
    a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)



(1, 3) (3, 4) (2, 4) (4, 3)
tf.Tensor(
[[ 9 18 14]
 [17 42 31]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 9, 18, 14],
       [17, 42, 31]], dtype=int32)>

In [ ]:
x_3.T = 4,2
x_2.T = 4,3

In [ ]:
x_3

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2,  0,  2],
       [ 3,  5, -1,  2]], dtype=int32)>

In [ ]:
x_1 = tf.constant([[10, 0],
                   [1,2]])
x_2 = tf.constant([[1,2,2],
                   [5,3,2]])
print(tf.linalg.matmul(x_1,x_2))

tf.Tensor(
[[10 20 20]
 [11  8  6]], shape=(2, 3), dtype=int32)


In [ ]:
tensor_two_d_m_n = tf.constant([[0,-1,2],
                                [1,0,-1],
                                [2,1,0],
                                [3,2,1]], dtype=tf.float16)
tensor_two_d_n_m = tf.constant([[0,1,2],
                                [2,0,1],
                                [-2,-1,0],
                                [-4,-2,-1]], dtype=tf.float16)


In [ ]:
x = tf.constant([1, 2, 3])
y = tf.broadcast_to(x, [3, 3])
print(y)

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [ ]:
tf.linalg.band_part(tensor_two_D, 0, -1)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float32)>

In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype=tf.float32)
tensor_two_d_inv = tf.linalg.inv(tensor_two_d)

tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.7413249 , -0.01892744,  0.3154574 ],
       [-0.12933753, -0.00946372,  0.15772872],
       [-0.01577287,  0.01104101, -0.01735016]], dtype=float32)>

In [ ]:
A = np.array([[[2, 6, 5, 0],
              [2, -2, 2, 2],
              [1, 5, 4, 0]],
             [[2, 6, 5, 0],
              [2, -2, 2, 2],
              [1, 5, 4, 0]]])

B = np.array([[[2, 9, 0, 3, 0],
              [3, 6, 8, -2, 2],
              [3, 3, 5, 0, 1],
              [3, 0, 2, 0, 4]],
              [[2, 9, 0, 3, 0],
              [3, 6, 8, -2, 2],
              [3, 3, 5, 0, 1],
              [3, 0, 2, 0, 4]]])


print("Batch multiplication c=: \n")
print(np.matmul(A,B), "\n")


print("Einsum c=: \n")
print(np.einsum('bij,bjk ->bik', A,B))

Batch multiplication c=: 

[[[37 69 73 -6 17]
  [10 12 -2 10  6]
  [29 51 60 -7 14]]

 [[37 69 73 -6 17]
  [10 12 -2 10  6]
  [29 51 60 -7 14]]] 

Einsum c=: 

[[[37 69 73 -6 17]
  [10 12 -2 10  6]
  [29 51 60 -7 14]]

 [[37 69 73 -6 17]
  [10 12 -2 10  6]
  [29 51 60 -7 14]]]


## Tensor Regged

In [ ]:
import tensorflow as tf
tensor_twoD = [[1,2,0],
               [3,],
               [1,5,6,5,6],
               [2,3]]

tensor_regged = tf.ragged.constant(tensor_twoD)
print(tensor_regged.shape)               
print(tensor_regged) 

(4, None)
<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>
